name = "xmin"
license = "MIT"
licenselink = "https://github.com/jatin-malik/hugo-xmin/blob/master/LICENSE.md"
description = "Minimal hugo theme"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[original]
  name = "Yihui Xie"
  homepage = "https://yihui.org"

[author]
  name = "Jatin Malik"
